pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "my-webpage-shh"
        DOCKER_TAG = "latest"
        DOCKER_REPO = "pavanthumati/my-webpage-shh"
        DOCKER_CREDENTIALS_ID = "DockerHubCredentials" // Jenkins credentials ID
        CONTAINER_NAME = "mycontainer11"
        CONTAINER_NAME1 = "mycontainer12"

    }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/PavanThumati/Training.git', branch: 'main'
            }
        }
        stage('Docker Login') {
            steps {
                script {
                    sh "docker pull nginx"
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        echo "Logged into Docker Hub"
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    
                    sh "docker build -f Docker/webpageThroughSSH/Dockerfile -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        sh "docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_REPO}:${DOCKER_TAG}"
                        sh "docker push ${DOCKER_REPO}:${DOCKER_TAG}"
                    }
                }
            }
        }
        stage('Deploy to Server') {
            steps {
                script {
                    sh """
                        sshpass -p "root" ssh -o StrictHostKeyChecking=no master@192.168.203.128 '
                        // docker pull ${DOCKER_REPO}:${DOCKER_TAG} &&
                        docker ps -a -q --filter name=${CONTAINER_NAME1} | xargs -r docker stop || true &&
                        docker ps -a -q --filter name=${CONTAINER_NAME1} | xargs -r docker rm || true &&
                        docker run -d -p 80:80 --name ${CONTAINER_NAME1} ${DOCKER_REPO}:${DOCKER_TAG}'
                    """
                }
            }
        }
    }
}
